apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: huggingface-transformer
  annotations:
    scenarios.ai.sap.com/description: "Run a huggingface-transformer on SAP AI Core"
    scenarios.ai.sap.com/name: "huggingface-transformer"
    executables.ai.sap.com/description: "huggingface-transformer service"
    executables.ai.sap.com/name: "huggingface-transformer"
  labels:
    scenarios.ai.sap.com/id: "huggingface-transformer"
    ai.sap.com/version: "0.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.l
    spec: |
      predictor:
        imagePullSecrets:
        - name: olamagit
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/jeyasinghsamuelponnusamydur043/transformer:ai-core-transformer
          ports:
            - containerPort: 8080
              protocol: TCP
